export const APP_ROUTES = {
    HOME: "/",
    COMPLEXES: "complexes",
    FLATS: "flats",
    FACING: "facing",
    MORTGAGE: "mortagage",
    INSTALLMENT: "installment",
    TRADE_IN: "trade-in",
    AUTO_TRADE_IN: "auto-trade-in",
    ABOUT: "about",
    FAVORITES: "favorites",
    PARTNERS: "partners",
    NEWS: "news",
    FMS: "fms",
    CAREER: "career",
    CONTACTS: "contacts",
    SUPPORT: "support",
    MEDIA: "media",
    DEVELOPMENT: "development",
};
