export const APP_ROUTES = {
    HOME: "/",
    COMPLEXES: "complexes",
    FLATS: "flats",
    FACING: "facing",
    MORTGAGE: "mortgage",
    INSTALLMENT: "installments",
    TRADE_IN: "trade-in",
    AUTO_TRADE_IN: "auto-trade-in",
    ABOUT: "about",
    FAVORITES: "favorites",
    PARTNERS: "partners",
    NEWS: "news-discounts",
    FMS: "fms",
    CAREER: "career",
    CONTACTS: "contacts",
    SUPPORT: "support",
    MEDIA: "media",
    DEVELOPMENT: "development",
    COMPARE: "compare",
};
